---
- hosts: all
  tasks:
    - name: Install requirements for WiSHFUL
      become: true
      apt: pkg={{ item }} state=present update_cache=true
      with_items:
      - wget
      - git
      - python3-pip

    - name: Make root dir writable
      become: true
      file:
        path: /root
        mode: "u+rwx,g+rwx,o+rwx"

    - name: Create WiSHFUL directory
      file:
        path: /root/wishful
        state: directory
        mode: "u+rwx,g+rwx,o+rwx"

    - name: Download repo file
      get_url:
        url: https://storage.googleapis.com/git-repo-downloads/repo
        dest: /root/wishful/repo

    - name: Make repo executable
      file:
        path: /root/wishful/repo
        mode: "a+x"

    - name: Init repo
      command: /root/wishful/repo init -u https://github.com/wishful-project/manifests.git
      args:
        chdir: /root/wishful/

    - name: Configure user-only manifest file
      command: /root/wishful/repo init -m user.xml
      args:
        chdir: /root/wishful/

    - name: get all repositories
      command: /root/wishful/repo sync
      args:
        chdir: /root/wishful/

    - name: create master branch on all
      command: /root/wishful/repo start master --all
      args:
        chdir: /root/wishful/

    - name: check status of all repositories
      command: /root/wishful/repo status
      args:
        chdir: /root/wishful/

    - replace:
        dest: /root/wishful/.repo/manifests/requirements.txt
        regexp: '\.'
        replace: '/root/wishful'

    - name: Install requirements
      become: true
      pip:
        requirements: /root/wishful/.repo/manifests/requirements.txt
        executable: pip3

    - name: Install test requirements
      become: true
      pip:
        requirements: /root/wishful/tests/requirements.txt
        executable: pip3
        
    - name: Install extra packages
      become: true
      pip:
        name: dnspython scapy
        executable: pip3

    - name: ntpdate sync for testing delayed calls
      ignore_errors: yes
      become: true
      shell: /usr/sbin/ntpdate time.google.com

- hosts: test_hosts
  tasks:
    - name: start agents on remote hosts
      become: true
      shell: /usr/bin/screen -DmS wishfulRemote -L -d -m /usr/bin/python3 /root/wishful/tests/common/remote_agent_host ; sleep 1

- hosts: test_controllers
  tasks:
    - name: Install DNSpython
      become: true
      pip:
        name: dnspython
        executable: pip3

    - name: Generate controller config file (including remote_hosts)
      become: true
      template:
        src: ../templates/controller_config.yaml.jn2
        dest: /root/wishful/tests/remote_hosts.yaml

    - name: Test WiSHFUL Core Remote
      become: true
      command: /usr/local/bin/pytest -s /root/wishful/tests/core/remote_test.py
      args:
        chdir: /root/wishful/tests/core/
      register: wishful_core_test_remote
      failed_when: "wishful_core_test_remote.rc != 0 or 'failed' in wishful_core_test_remote.stdout_lines"
    - debug: var=wishful_core_test_remote.stdout_lines

- hosts: test_hosts
  tasks:
    - name: kill wishfulRemote screen sessions
      become: true
      shell: /usr/bin/screen -X -S wishfulRemote quit

