#!/bin/bash
export LC_ALL=C

#control while setting up the experiment---------------------------------------
CONTROLINT=ERROR
CONTROLIP=ERROR
HOST=ERROR
YEPKITID=ERROR
DEV=ERROR
DEVNAME=ERROR
DATE=`date '+%y_%h_%d-%H_%M_%S'`

function finalize()
{
	result=`printf "=====%s, %s, %s, %s, %s, %s, %s, %s, %s =====\n" $CONTROLINT $CONTROLIP $HOST $YEPKITID $DEV $DEVNAME $NODE $EXP $DATE`
	echo $result
	sudo deluser `whoami` dialout
	exit 0
}

#setup working dirs and vars---------------------------------------------------
WSNBIN=waves-rssi.bin
PWD=`pwd`
MYDIR=`dirname $0`
echo will switch from $PWD to $MYDIR
cd $MYDIR
BIN=`pwd`

#hostname is generated by emulab, virtual space in experiment------------------
HOSTNAME=`hostname`
EXP=`echo $HOSTNAME | cut -d '.' -f 2`
NODE=`echo $HOSTNAME | cut -d '.' -f 1`
NODEEXT=`echo $HOSTNAME | cut -d '.' -f 2-`
#assign node0 of this experiment as RSSIserver
RSSISERVERHOST=`echo node0.$NODEEXT`
MYSQLSERVERPORT=3306
#retrieve the ref node testbed name (location is important) of the node--------
CONTROLINT=`route -n | awk '{print $4 " " $8}' | grep UG | awk '{print $2}'`
CONTROLIP=`ifconfig $CONTROLINT | grep 'inet addr' | awk '{print $2} ' | cut -d ':' -f 2` 
HOST=`dig +noall +answer -x $CONTROLIP | awk '{print $5}' | sed 's/\.$//'`
HOSTSHORT=`echo $HOST | cut -d '.' -f 1`

#yepkit related----------------------------------------------------------------
if [ -z "`dpkg -l | grep libhidapi-libusb0`" ]; then
	sudo /share/yepkit-USB-hub/missing-lib.sh
fi 

YEPKITID=`/share/yepkit-USB-hub/ykushcmd -l | grep Serial | awk '{print $7}'`
if [ -z $YEPKITID ]; then
	YEPKITID=ERROR
	finalize
fi

sudo /share/yepkit-USB-hub/ykushcmd -d 1
sudo /share/yepkit-USB-hub/ykushcmd -d 2
sudo /share/yepkit-USB-hub/ykushcmd -d 3
sudo /share/yepkit-USB-hub/ykushcmd -u 1
#sudo /share/yepkit-USB-hub/ykushcmd -u 2
#sudo /share/yepkit-USB-hub/ykushcmd -u 3

echo "will try motelist..."
sleep 1
DEV=`motelist -c | tail -n 1 | grep '/dev/' | cut -d ',' -f 2`
if [ -z $DEV ]; then 
	DEV=ERROR
	finalize
fi 
DEVNAME=`motelist -c | cut -d ',' -f 1`

#packages----------------------------------------------------------------------
sudo apt-get update
sudo apt-get install libdbi-perl libdbd-mysql-perl

if [ "$NODE" == "node0" ]; then
	#unattended mysqld install
	export DEBIAN_FRONTEND=noninteractive
	sudo -E apt-get -q -y install mysql-server
	sudo mysqladmin -u root password wavesrssi
	sudo mysql -uroot -pwavesrssi < initwavesdb.sql
	#make it available over the network
	sudo sed 's/\(^.*bind-address.*$\)/#\1/' -i /etc/mysql/mysql.conf.d/mysqld.cnf
	sudo service mysql restart
else
	#wait until the server becomes available
	SERVERAVAILABLE=0
	RETRIES=60
	while [ "$SERVERAVAILABLE" -eq "0" -a "$RETRIES" -gt "0" ]; do
        if [ ! "" = "`sudo /usr/bin/nmap -PN -n $RSSISERVERHOST -p $MYSQLSERVERPORT -g $MYSQLSERVERPORT 2>/dev/null | grep 'tcp open' 2>/dev/null`" ]; then
                SERVERAVAILABLE=1
        else
                sleep 5
                RETRIES=$((RETRIES - 1))
                echo Will wait for server $RSSISERVERHOST for another $((RETRIES*5)) seconds
         fi
	done
fi

sudo adduser `whoami` dialout
while true;  do
	sg dialout "python cc2538-bsl.py -e -w -v -a 0x00206000 -p $DEV -i ab:cd:00:ff:fe:00:00:1 $WSNBIN 2>&1"
	sg dialout "$BIN/parseSerialDump.pl $HOSTSHORT $DEV $RSSISERVERHOST"
done
finalize

