# ansible playbook, test file for ftester & wilab2
# v0.1
# author: vsercu@intec.ugent.be

# - fixed lijst van nodes
# - msp430 v4.7.3 op nodes
# - python depts libclang versie ??

---
# distribute the git-scripts that were pulled by flsmon
- name: distribute git files among nodes
  hosts : all
  tasks :
    - name : distribute scripts
      # copy assumes git clone https://github.com/WirelessTestbedsAcademy/ExperimentationTools.git
      copy: 
        src: ./ 
        dest: /tmp/git-checkout-temptest/ 
        directory_mode: '0775'
        force: yes
         
# execute the run-script
- name: temptest
  hosts: all
  # sudo: True
  tasks:
   - name: run_temptest_script
     shell:  "/tmp/git-checkout-temptest/run.sh"
     register: temp_test
     failed_when: "'ERROR' in temp_test.stdout_lines"
   - debug: var=temp_test.stdout_lines
    
