## WiSHFUL Agent config file

agent_info:
    name: 'contiki_control_agent'
    info: 'WiSHFUL example Contiki control agent'
    iface: 'INTERFACE'

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryAgentModule
        kwargs: {"iface":INTERFACE, "groupName":"wishful_contiki"}
    gitar_engine:
        module : wishful_module_gitar
        class_name : GitarEngine
        interfaces : [NODE_LIST]
        kwargs :
            GitarConfig : 'GITAR_CONFIG'
            SupportedInterfaces : [NODE_LIST]
    generic_connector:
        module : wishful_module_generic
        class_name : GenericConnector
        interfaces : [NODE_LIST]
        kwargs :
            SupportedInterfaces : [NODE_LIST]
            ControlAttributes : {"generic_connector": './config/protocol_connectors/generic_ctrl_attributes.csv'}
            ControlFunctions : {"generic_connector": './config/protocol_connectors/generic_ctrl_functions.csv'}
            ProtocolConnectors: {"generic_connector": 0}
    taisc_connector:
        module : wishful_module_taisc
        class_name : TAISCConnector
        interfaces : [NODE_LIST]
        kwargs :
            RadioPrograms : {"CSMA":0,"TDMA":2,"TSCH":1}
            SupportedInterfaces : [NODE_LIST]
            ControlAttributes : {'taisc_connector': './config/protocol_connectors/taisc_ctrl_attributes.csv'}
            ControlFunctions : {'taisc_connector': './config/protocol_connectors/taisc_ctrl_functions.csv'}
            ProtocolConnectors: {'taisc_connector': 3}
    ipv6_connector:
        module : wishful_module_ipv6
        class_name : IPv6Connector
        interfaces : [NODE_LIST]
        kwargs :
            SupportedInterfaces : [NODE_LIST]
            ControlAttributes : {'ipv6_connector': './config/protocol_connectors/ipv6_ctrl_attributes.csv', 'rpl_connector': './config/protocol_connectors/rpl_ctrl_attributes.csv'} 
            ControlFunctions : {'ipv6_connector': './config/protocol_connectors/ipv6_ctrl_functions.csv', 'rpl_connector': './config/protocol_connectors/rpl_ctrl_functions.csv'}
            ProtocolConnectors: {'ipv6_connector': 1, 'rpl_connector': 2}
